;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        beginning-of-buffer
        c-electric-colon
        c-electric-delete-forward
        c-electric-paren
        c-electric-semi&comma
        c-electric-star
        coffee-dedent-line-backspace
        company-coq-maybe-exit-snippet
        company-ignore
        coq-terminator-insert
        dabbrev-expand
        delete-horizontal-space
        delete-indentation
        electric-newline-and-maybe-indent
        ensime-company-complete-or-indent
        forward-sexp
        go-mode-insert-and-indent
        haskell-indentation-delete-backward-char
        kill-region
        kill-sexp
        org-beginning-of-line
        org-delete-char
        org-end-of-line
        org-force-self-insert
        org-kill-line
        orgtbl-hijacker-command-102
        paredit-backward-kill-word
        paredit-forward-delete
        paredit-forward-kill-word
        paredit-splice-sexp
        yaml-electric-backspace
        yaml-electric-dash-and-dot
        ))

(setq mc/cmds-to-run-once
      '(
        end-of-buffer
        ensime-backward-note
        ensime-mouse-motion
        ido-find-file
        ido-switch-buffer
        ignore
        indent-for-tab-command
        org-self-insert-command
        orgtbl-self-insert-command
        pg-protected-undo
        undefined
        ))
