;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-delete-forward
        c-electric-paren
        c-electric-star
        coffee-dedent-line-backspace
        company-ignore
        dabbrev-expand
        haskell-indentation-delete-backward-char
        kill-region
        orgtbl-hijacker-command-102
        paredit-backward-kill-word
        paredit-forward-kill-word
        ))

(setq mc/cmds-to-run-once
      '(
        ido-switch-buffer
        indent-for-tab-command
        orgtbl-self-insert-command
        ))
